#' Simulated Similarity dataset for use in Clarity
#'
#' A dataset containing the similarities generated by the following:
#'
#' \code{set.seed(1)}
#' \code{mysim<-simulateCoalescent(100,10,rep(0.2,10))} # Simlulate 100 objects in a 10 dimensional latent space
#' \code{myroworder=order(apply(mysim$A,1,which.max))}
#' \code{mysim$A=mysim$A[myroworder,]}
#' mysim$Y=mysim$Y[myroworder,myroworder]
#' mysim$Y0=mysim$Y0[myroworder,myroworder]
#' dataraw=mysim$Y
#' 
#' @format A non-negative similarity matrix of dimension 100 by 100
#' 
#' @source Uses Package \code{\link[ClaritySim]{ClaritySim}}
"dataraw"

#' Simulated Similarity dataset with modified branch lengths for use in Clarity
#'
#' A dataset containing the similarities generated by changing branch lengths of \code{\link{dataraw}} using \code{\link[ClaritySim]{transformCoalescent}} from package \code{\link[ClaritySim]{ClaritySim}}
#' 
#' 
#' @format A non-negative similarity matrix of dimension 100 by 100
#' 
#' @source Uses Package \code{\link[ClaritySim]{ClaritySim}}
"datarep"

#' Simulated Similarity dataset with modified topology for use in Clarity
#'
#' A dataset containing the similarities generated by changing branch lengths of \code{\link{dataraw}} using \code{\link[ClaritySim]{mixCoalescent}} from package ClaritySim
#' 
#' 
#' @format A non-negative similarity matrix of dimension 100 by 100
#' 
#' @source Uses Package \code{\link[ClaritySim]{ClaritySim}}
"datamix"
