#' @title Simulated Similarity dataset for use in Clarity
#'
#' @description
#' A matrix containing the true clustering for the generated by the following:
#'
#' \code{library(ClaritySim)}
#' \code{set.seed(1)}
#' # Simlulate 100 objects in 10 hierarchically related clusters with 500 features
#' \code{mysim=simulateCoalescent(N=100,K=10,L=500,
#'                             alpha=0,
#'                             sigma0=0.0001,Amodel="uniform",
#'                             minedge=0.1)}
#' \code{datarawA=mysim$A}
#' 
#' @format A non-negative mixture matrix of dimension 100 by 10
#' @seealso Mixture matrix \code{\link{datarawA}}, Feature matrix \code{\link{datarawD}}, Similarity matrix \code{\link{dataraw}}, Similarity matrix with same topology \code{\link{datarep}}, Similarity matrix with different topology \code{\link{datamix}}.
#' @source Uses Package \code{\link[ClaritySim]{ClaritySim}}
"datarawA"

#' @title Simulated Similarity dataset for use in Clarity
#'
#' @description
#' A matrix containing the features for the generated by the following:
#'
#' \code{library(ClaritySim)}
#' \code{set.seed(1)}
#' # Simlulate 100 objects in 10 hierarchically related clusters with 500 features
#' \code{mysim=simulateCoalescent(N=100,K=10,L=500,
#'                             alpha=0,
#'                             sigma0=0.0001,Amodel="uniform",
#'                             minedge=0.1)}
#' \code{datarawD=mysim$D}
#' 
#' @format A non-negative features matrix of dimension 100 by 500
#' @seealso Mixture matrix \code{\link{datarawA}}, Feature matrix \code{\link{datarawD}}, Similarity matrix \code{\link{dataraw}}, Similarity matrix with same topology \code{\link{datarep}}, Similarity matrix with different topology \code{\link{datamix}}.
#' 
#' @source Uses Package \code{\link[ClaritySim]{ClaritySim}}
"datarawD"

#' @title Simulated Similarity dataset for use in Clarity
#'
#' @description
#' A dataset containing the similarities generated by the following:
#'
#' \code{library(ClaritySim)}
#' \code{set.seed(1)}
#' # Simlulate 100 objects in 10 hierarchically related clusters with 500 features
#' \code{mysim=simulateCoalescent(N=100,K=10,L=500,
#'                             alpha=0,
#'                             sigma0=0.0001,Amodel="uniform",
#'                             minedge=0.1)}
#' \code{dataraw=mysim$Y}
#' 
#' @format A non-negative similarity matrix of dimension 100 by 100
#' @seealso Mixture matrix \code{\link{datarawA}}, Feature matrix \code{\link{datarawD}}, Similarity matrix \code{\link{dataraw}}, Similarity matrix with same topology \code{\link{datarep}}, Similarity matrix with different topology \code{\link{datamix}}.
#' 
#' @source Uses Package \code{\link[ClaritySim]{ClaritySim}}
"dataraw"

#' @title Simulated Similarity dataset with modified branch lengths for use in Clarity
#'
#' @description
#' A dataset containing the similarities generated by changing branch lengths of \code{\link{dataraw}}
#'
#' \code{library(ClaritySim)}
#' \code{set.seed(1)}
#' # Simlulate 100 objects in 10 hierarchically related clusters with 500 features
#' \code{mysim=simulateCoalescent(N=100,K=10,L=500,
#'                             alpha=0,
#'                             sigma0=0.0001,Amodel="uniform",
#'                             minedge=0.1)}
#' # transform the branch lengths and regenerate features and similarity
#' \code{repsim<-transformCoalescent(mysim)}
#' \code{datarep=repsim$Y}
#' 
#' @format A non-negative similarity matrix of dimension 100 by 100
#' @seealso Mixture matrix \code{\link{datarawA}}, Feature matrix \code{\link{datarawD}}, Similarity matrix \code{\link{dataraw}}, Similarity matrix with same topology \code{\link{datarep}}, Similarity matrix with different topology \code{\link{datamix}}.
#' 
#' @source Uses Package \code{\link[ClaritySim]{ClaritySim}}
"datarep"

#' @title Simulated Similarity dataset with modified topology for use in Clarity
#'
#' @description
#' A dataset containing the similarities generated by changing branch lengths and topoligical structure of \code{\link{dataraw}}
#'
#' \code{library(ClaritySim)}
#' \code{set.seed(1)}
#' # Simlulate 100 objects in 10 hierarchically related clusters with 500 features
#' \code{mysim=simulateCoalescent(N=100,K=10,L=500,
#'                             alpha=0,
#'                             sigma0=0.0001,Amodel="uniform",
#'                             minedge=0.1)}
#' # transform the branch lengths and regenerate features and similarity
#' \code{mixsim<-mixCoalescent(mysim)}
#' \code{datamix=mixsim$Y}
#' 
#' @format A non-negative similarity matrix of dimension 100 by 100
#' @seealso Mixture matrix \code{\link{datarawA}}, Feature matrix \code{\link{datarawD}}, Similarity matrix \code{\link{dataraw}}, Similarity matrix with same topology \code{\link{datarep}}, Similarity matrix with different topology \code{\link{datamix}}.
#' 
#' @source Uses Package \code{\link[ClaritySim]{ClaritySim}}
"datamix"
